s3:
  enable: true

aws:
  # tmp access key & securet, will destroy after commit code to GitHub
  access-key: AKIAZGHWLJCCKGZXTIH4
  secret-key: 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
  # default region: us-east-1
  region: ${AWS_REGION:us-east-1}

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: custom-spring-starter-example-app

server:
  port: 8080
